### ISSUE TITLE
推理过程有问题

### ISSUE THREAD

**Issue by meareabc** [wnma3mz/llama#2]
0 1
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
Loaded in 8.13 seconds
hello how are you?

==================================

It was all so friendly, relaxed and informal. There was no posing, no setting up – it was a conversation between the two photographers and the models. It was lovely to see the chemistry between the photographers and the models.
We both felt very comfortable and relaxed and I really enjoyed the experience. It was so inspiring to see such a beautiful, elegant and chic shoot and I can’t wait to shoot again.
Thanks a million to Pauline and Elena for a lovely afternoon.
You can check out Elena’s blog to see more of the lovely shots she took.
Tagged Fashion photography, Elena Temnikova, Pauline O'Connor, Models, Model photography
Previous Post Portraits of a humanist wedding
Next Post Fashion photography: I am a fashion model
One thought on “Fashion photography: I am a fashion model”
Pingback: A day at the races | Annie Campbell Photography Home › Posts tagged Zombies
Tag: Zombies
The Walking Dead: Tyreese and Chad DeMott
The Walking Dead

在同样的ckpt下，与LLAMA原始代码的推理效果出现较大差异

**Comment by wnma3mz** [comment]
这个加载时间应该是正常的。

试试官方提供的prompt？我这边测下来性能应该和原ckpt的没差，我之后有时间跑一下我这边的结果。

**Comment by meareabc** [comment]
> 这个加载时间应该是正常的。
> 
> 试试官方提供的prompt？我这边测下来性能应该和原ckpt的没差，我之后有时间跑一下我这边的结果。

我最近在用transformers的hf格式在跑了，LLAMA这种pth感觉不太便捷
另外我的意思是，对于LLAMA发布的同一个预训练文件，在您的generate结果和LLAMA主页的结果不一致，而且您的结果会出现上面逻辑不通的情况。

**Comment by wnma3mz** [comment]
了解，我这边测试后的时候并没有这个问题，之后有空再看看是不是有啥Bug导致这一问题。理论上在保证参数+随机种子相同的情况下，生成质量应该相差无几。
